### PR TITLE
Update answers on Uni Hamburg Wikidata SPARQL Endpoint

### PR DESCRIPTION
**Pull request by Perevalov**
- [x] Update Test set
- [x] Update Train set

### CODE REVIEW

**Comment by Perevalov** [comment]
Some of the results of the queries with **no sorting** (e.g. What is the time zone of Salt-Lake-City?) are **identical**, however, have different results order which resulted in the huge file difference but does not affect the correctness.

**Comment by janreineke** [comment]
There is a ' "timeout": 300' in qald_9_plus_test_wikidata.json on line 121178.

**Comment by Perevalov** [comment]
> There is a ' "timeout": 300' in qald_9_plus_test_wikidata.json on line 121178.

Yes you are right, the following lines have this error:
```bash
qald_9_plus_test_wikidata.json:121178:                    "timeout": 300
qald_9_plus_test_wikidata.json:123031:                    "timeout": 300
qald_9_plus_train_wikidata.json:78499:                    "timeout": 300
qald_9_plus_train_wikidata.json:279196:                    "timeout": 300
qald_9_plus_train_wikidata.json:279488:                    "timeout": 300
qald_9_plus_train_wikidata.json:312957:                    "timeout": 300
```

I tried one of the queries with `cURL`: 
```bash
curl -H 'Accept: application/sparql-results+json' http://sems-vm-1.informatik.uni-hamburg.de:443/api/endpoint/sparql --data-urlencode 'query=SELECT DISTINCT ?uri WHERE { ?uri <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q82955> . ?uri <http://www.wikidata.org/prop/direct/P26> ?spouse . { ?spouse <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183> . } UNION { ?spouse <http://www.wikidata.org/prop/direct/P19>/<http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q183> } }'
```

and got the same response with timeout error. On the official endpoint it's executable. Could it be possible to configure the timeout for the endpoint?

**Comment by RicardoUsbeck** [comment]
@cedricm-research can you increase the timeout?

**Comment by RicardoUsbeck** [comment]
"There are 77 empty results for train and 18 for test. However, on the current Wikidata some of the return the actual results" => But they should run on the provided dump for replicability. Thus, I vote for removing them. What do you think?

**Comment by Perevalov** [comment]
> "There are 77 empty results for train and 18 for test. However, on the current Wikidata some of the return the actual results" => But they should run on the provided dump for replicability. Thus, I vote for removing them. What do you think?

Is it necessary if QALD-9-Plus is used just for train/validation? 

If we decide to remove them, I suggest to merge it to a separate branch (e.g. `qald-x-challenge`), because some of the results are empty just on the deployed endpoint not on the live Wikidata.

**Comment by RicardoUsbeck** [comment]
I agree. 

Those who run on the static endpoint should be copied to qald-10-train.json and provided in a different repo, i.e., https://github.com/KGQA/QALD_10

WDYT?

**Comment by Perevalov** [comment]
> I agree.
> 
> Those who run on the static endpoint should be copied to qald-10-train.json and provided in a different repo, i.e., https://github.com/KGQA/QALD_10
> 
> WDYT?

Let's do this, I will create the repo and push the data w/o empty answers

**Comment by Perevalov** [comment]
> > I agree.
> > Those who run on the static endpoint should be copied to qald-10-train.json and provided in a different repo, i.e., https://github.com/KGQA/QALD_10
> > WDYT?
> 
> Let's do this, I will create the repo and push the data w/o empty answers

@RicardoUsbeck please check https://github.com/KGQA/QALD_10/pull/1

**Comment by RicardoUsbeck** [comment]
LGTM now. How about @janreineke or @julius?

**Comment by JSchulz747** [comment]
https://github.com/KGQA/QALD_10 looks fine to me.

**Comment by Perevalov** [comment]
@RicardoUsbeck I think we have to revert this one, as we decided to go to QALD_10 repo

**Comment by RicardoUsbeck** [comment]
Ohhhhh true, my bad sorry! Feel free to revert it

**Pull request merged**
